'use client';
import { Leaf, Upload } from 'lucide-react';
import { useState } from 'react';
import { SectionTitle } from './Sections';

export function CustomPreview() {
  const [custom, setCustom] = useState({ flower: 'Rose', name: 'Amara', color: 'Dusty Rose', flakes: true, shape: 'Oval', budget: '₹2,000 - ₹5,000', timeline: '3 weeks' });
  return <section className="bg-ivory px-6 py-28"><SectionTitle eyebrow="Personal atelier" title="Design a keepsake in real time" text="Choose product, flowers, names, colors, gold flakes, shape, budget, timeline, notes, and upload inspiration images." /><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><form data-reveal className="glass rounded-[3rem] p-8"><div className="mb-7 flex items-center gap-2"><span className="h-2 flex-1 rounded-full bg-gold" /><span className="h-2 flex-1 rounded-full bg-sage" /><span className="h-2 flex-1 rounded-full bg-rose" /></div><div className="grid gap-4 md:grid-cols-2">{(['flower', 'name', 'color', 'shape', 'budget', 'timeline'] as const).map((key) => <label key={key} className="text-sm font-semibold capitalize">{key}<input className="mt-2 w-full rounded-2xl border bg-white p-4" value={custom[key] as string} onChange={(event) => setCustom({ ...custom, [key]: event.target.value })} /></label>)}<label className="md:col-span-2 flex items-center gap-3 rounded-2xl bg-white p-4"><input type="checkbox" checked={custom.flakes} onChange={(event) => setCustom({ ...custom, flakes: event.target.checked })} /> Add champagne gold flakes</label><textarea className="md:col-span-2 min-h-32 rounded-2xl border bg-white p-4" placeholder="Notes, occasion, recipient, flower preservation details" /><label className="md:col-span-2 rounded-2xl border border-dashed bg-white p-6 text-center"><Upload className="mx-auto mb-2 text-gold" />Upload inspiration images</label></div></form><div data-reveal className="rounded-[3rem] bg-white p-10 shadow-boutique"><div className="mx-auto grid h-80 w-64 place-items-center rounded-[50%] bg-gradient-to-br from-rose/50 via-white to-sage/40 shadow-glow"><div className="text-center"><Leaf className="mx-auto text-sage" size={44} /><h3 className="font-heading text-5xl">{custom.name}</h3><p>{custom.flower} · {custom.color} · {custom.shape}</p>{custom.flakes && <p className="mt-2 text-gold">Champagne gold flakes</p>}<p className="mt-4 text-xs uppercase tracking-[.25em] text-charcoal/50">{custom.budget} · {custom.timeline}</p></div></div></div></div></section>;
}
